feat(lambda): Added FunctionURLConfig resource
crossplane-contrib/provider-aws pull request #1554
Opened 2022-11-04 20:28 UTC by pintonunes

### Description of your changes

Added Lambda FunctionURLConfig resource

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
- `make run` in a test cluster
- tested create / update / delete
- tested using an existing Function resource as ref

[contribution process]: https://git.io/fj2m9

2022-11-07 14:58 UTC, MisterMX commented
Thanks for your contribution @pintonunes. Could you add an example to resource as well?

2022-11-08 13:55 UTC, pintonunes commented
@MisterMX, added example.

2022-11-08 14:31 UTC, MisterMX requested changes
Looks already good. Thank you @pintonunes. Almost ready to merge. Just some minor remarks.

2022-11-08 15:41 UTC, pintonunes commented on pkg/controller/lambda/functionurlconfig/setup.go
> +		return false
What you mean? You mean the all cases with return false? I wrote that way cause is easy to read than having a huge case/if line.

2022-11-08 18:37 UTC, pintonunes commented
@MisterMX after merging the #1259 the check-diff started to fail. 
18:24:01 [ .. ] checking that branch is clean
 M apis/batch/v1alpha1/zz_compute_environment.go
 M apis/batch/v1alpha1/zz_enums.go
 M apis/batch/v1alpha1/zz_generated.deepcopy.go
 M apis/batch/v1alpha1/zz_job_queue.go
 M apis/batch/v1alpha1/zz_types.go
 M package/crds/batch.aws.crossplane.io_computeenvironments.yaml
 M package/crds/batch.aws.crossplane.io_jobqueues.yaml
 M pkg/controller/batch/computeenvironment/zz_conversions.go
 M pkg/controller/batch/jobqueue/zz_conversions.go
 
Go sdk was updated to 1.44 and that will generate more stuff that was not included on #1259

2022-11-10 09:49 UTC, MisterMX commented
The check-diff error has been fixed in https://github.com/crossplane-contrib/provider-aws/pull/1561. @pintonunes can you rebase on the latest master?

2022-11-10 12:09 UTC, pintonunes commented
done @MisterMX

2022-11-10 15:56 UTC, MisterMX commented on pkg/controller/lambda/functionurlconfig/setup.go
> +		return false
Yes, you can combine all `false` conditions into one `case` to make it more readable:

```go
switch {
case !cmp.Equal(&cr.Spec.ForProvider.CORS.ExposeHeaders, &obj.Cors.ExposeHeaders, sortCmp), aws.Int64Value(cr.Spec.ForProvider.CORS.MaxAge) != aws.Int64Value(obj.Cors.MaxAge):
	return false
}
```

2022-11-14 09:13 UTC, merged