chore: Document field error on S3 Bucket types
crossplane-contrib/provider-aws pull request #1575
Opened 2022-11-16 10:10 UTC by achetronic

### Description of your changes

Just add a bit of documentation in the field locationConstraint for S3 buckets, to help people to debug some "error dialing" given by AWS and not by the provider

Fixes #

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

2022-11-17 20:54 UTC, haarchri commented
Can you run make generate locally ?

2022-11-19 01:22 UTC, achetronic commented
> Can you run make generate locally ?

Yes! :) Sorry, I forgot. Manifest generated and added to the PR

2022-11-21 15:33 UTC, MisterMX requested changes

2022-11-21 15:33 UTC, MisterMX commented on apis/s3/v1beta1/bucket_types.go
> +	// about the problem, producing some errors related to dial
```suggestion
	// Due to AWS API limitations lacking on a proper response, when this field is set to a wrong value,
	// or to non-existent region on bucket creation, it's impossible forwarding a meaningful status message to the user
	// about the problem, producing connection errors instead.
```

2022-11-22 08:35 UTC, merged

2022-11-22 09:09 UTC, achetronic commented
> LGTM. Thanks @achetronic!

Thank you and @haarchri for guiding me on this :)