feat(rds): added rds optiongroup
crossplane-contrib/provider-aws pull request #1690
Opened 2023-03-05 16:57 UTC by haarchri

### Description of your changes
added rds optiongroup
added generic functions for tagging in rds apiGroup

Fixes #1530

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
- create
- update options
- update tags
- delete

```
kubectl get optiongroup
NAME      READY   SYNCED   EXTERNAL-NAME
example   True    True     example
```

```
Name:         example
Namespace:    
Labels:       <none>
Annotations:  crossplane.io/external-create-pending: 2023-03-05T17:29:25+01:00
              crossplane.io/external-create-succeeded: 2023-03-05T17:29:25+01:00
              crossplane.io/external-name: example
API Version:  rds.aws.crossplane.io/v1alpha1
Kind:         OptionGroup
[...]
Spec:
  Deletion Policy:  Delete
  For Provider:
    Engine Name:           sqlserver-ee
    Major Engine Version:  11.00
    Option:
      Option Name:  TDE
      Option Name:  SQLSERVER_BACKUP_RESTORE
      Option Settings:
        Name:                  IAM_ROLE_ARN
        Value:                 arn:aws:iam::12345678910:role/sqlserver-backup-restore
    Option Group Description:  example
    Region:                    us-east-1
    Tags:
      Key:    optiongroup
      Value:  example-optiongroup
  Provider Config Ref:
    Name:  default
Status:
  At Provider:
    Allows VPC And Non VPC Instance Memberships:  false
    Option Group ARN:                             arn:aws:rds:us-east-1:12345678910:og:example
    Option Group Name:                            example
    Options:
      Option Description:  SQLServer Database Level Customer Backups and Restores
      Option Name:         SQLSERVER_BACKUP_RESTORE
      Option Settings:
        Apply Type:        DYNAMIC
        Data Type:         STRING
        Description:       Specifies the IAM role ARN used by RDS to backup and restore to and from customer's S3 bucket(s)
        Is Collection:     false
        Is Modifiable:     true
        Name:              IAM_ROLE_ARN
        Value:             arn:aws:iam::12345678910:role/sqlserver-backup-restore
      Permanent:           false
      Persistent:          false
      Option Description:  SQL Server - Transparent Data Encryption
      Option Name:         TDE
      Permanent:           false
      Persistent:          true
  Conditions:
    Last Transition Time:  2023-03-05T16:29:25Z
    Reason:                Available
    Status:                True
    Type:                  Ready
    Last Transition Time:  2023-03-05T16:29:25Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced

```

[contribution process]: https://git.io/fj2m9

2023-03-06 12:23 UTC, MisterMX requested changes

2023-03-06 12:23 UTC, MisterMX commented on examples/iam/role.yaml
> +  name: sqlserver-backup-restore
```suggestion
  name: rds-role
```

2023-03-07 13:06 UTC, MisterMX approved these changes
LGTM. Thanks @haarchri

2023-03-07 13:07 UTC, merged

2023-03-07 13:09 UTC, dudicoco commented
Thanks @haarchri!